version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: Final_Brasilian-t
    restart: unless-stopped
    environment:
      POSTGRES_DB: FinalBrasilian-t
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20-24-Dn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Brasiliant-network

volumes:
  postgres_data:

networks:
  Brasiliant-network: